export const AMBASSADORS_DATA = [
  {
    id: 'matthew-berman',
    name: 'Matthew Berman',
    image: '/ambassadors/matthew-berman.jpg',
    link: 'https://www.youtube.com/@matthew_berman',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'sam-witteveen',
    name: 'Sam Witteveen',
    image: '/ambassadors/sam-witteveen.png',
    link: 'https://www.youtube.com/@samwitteveenai',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'johann-diep',
    name: 'Johann Diep',
    image: '/ambassadors/johann-diep.jpeg',
    link: 'https://www.linkedin.com/in/johann-diep/',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'chansung-park',
    name: 'Chansung Park',
    image: '/ambassadors/chansung-park.png',
    link: 'https://github.com/deep-diver',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'alexey-shabanov',
    name: 'Alexey Shabanov',
    image: '/ambassadors/alexey-shabanov.jpg',
    link: 'https://www.testingcatalog.com/author/alexey/',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'gijsbert-westeneng',
    name: 'Gijsbert Westeneng',
    image: '/ambassadors/gijsbert-westeneng.jpeg',
    link: 'https://www.linkedin.com/in/gijsbert-westeneng-804172155/',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'francesco-capuano',
    name: 'Francesco Capuano',
    image: '/ambassadors/francesco-capuano.jpeg',
    link: 'https://www.linkedin.com/in/fracapuano/',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'guohao-li',
    name: 'Guohao Li',
    image: '/ambassadors/guohao-li.png',
    link: 'https://x.com/guohao_li',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'jean-baptiste-viet',
    name: 'Jean-Baptiste Viet',
    image: '/ambassadors/jean-baptiste-viet.jpg',
    link: 'https://youtube.com/@jeanviet',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'alfonso-amayuelas',
    name: 'Alfonso Amayuelas',
    image: '/ambassadors/alfonso-amayuelas.jpg',
    link: 'https://www.amayuelas.me/',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'boris-lesueur',
    name: 'Boris Lesueur',
    image: '/ambassadors/boris-lesueur.png',
    link: 'https://www.youtube.com/channel/UCMJEpQVv0p3qzJnQ9IuiiMA',
    bio: 'Mistral AI expert and community contributor',
    specialties: ['Machine Learning', 'AI Development', 'Community Building'],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'pierre-bittner',
    name: 'Pierre Bittner',
    image: '/ambassadors/pierre-bittner.png',
    link: 'https://www.youtube.com/@pierrebittner',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'r-shyaam-prasadh',
    name: 'R. Shyaam Prasadh',
    image: '/ambassadors/m-rainbow.svg',
    link: 'https://www.linkedin.com/in/sprasadh/',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'kristian-kagerlie',
    name: 'Kristian Fagerlie',
    image: '/ambassadors/m-rainbow.svg',
    link: 'https://www.youtube.com/allaboutai',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'stephen-batifol',
    name: 'Stephen Batifol',
    image: '/ambassadors/m-rainbow.svg',
    link: 'https://www.linkedin.com/in/stephen-batifol/',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'aryan-kargwal',
    name: 'Aryan Kargwal',
    image: '/ambassadors/aryan-kargwal.png',
    link: 'https://www.linkedin.com/in/aryankargwal',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'bradney-smith',
    name: 'Bradney Smith',
    image: '/ambassadors/bradney-smith.jpg',
    link: 'https://www.linkedin.com/in/bradney-smith/',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'darius-bittle-dockery',
    name: 'Darius Bittle Dockery',
    image: '/ambassadors/darius-bittle-dockery.jpeg',
    link: 'https://linkedin.com/in/dariusbdockery',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'eric-jacopin',
    name: 'Eric Jacopin',
    image: '/ambassadors/eric-jacopin.png',
    link: 'https://github.com/PCfVW',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'fahd-mirza',
    name: 'Fahd Mirza',
    image: '/ambassadors/fahd-mirza.png',
    link: 'https://www.youtube.com/@fahdmirza',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'james-briggs',
    name: 'James Briggs',
    image: '/ambassadors/james-briggs.jpeg',
    link: '',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'priyanka-madiraju',
    name: 'Priyanka Madiraju',
    image: '/ambassadors/priyanka-madiraju.jpg',
    link: 'https://www.linkedin.com/in/priyanka-madiraju/',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'soukaina-tichirra',
    name: 'Soukaina Tichirra',
    image: '/ambassadors/soukaina-tichirra.jpg',
    link: 'https://www.instagram.com/glimps_ofsc/',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'venkata-ramanand-cheedella',
    name: 'Venkata Ramanand Cheedella',
    image: '/ambassadors/venkata-ramanand-cheedella.jpeg',
    link: 'https://www.linkedin.com/in/venkata-cheedella/',
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'doa',
    name: 'Doaa Serageldin',
    image: "/ambassadors/doaa-serageldin.png",
    link: "",
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'jose-iranzo',
    name: 'José Iranzo',
    image: "/ambassadors/jose-iranzo.jpg",
    link: "https://www.reddit.com/user/Nefhis/",
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'saumya-gautam',
    name: 'Saumya Gautam',
    image: "/ambassadors/m-rainbow.svg",
    link: "",
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'boris-kharitontsev',
    name: 'Boris Kharitontsev',
    image: "/ambassadors/m-rainbow.svg",
    link: "",
    bio: '',
    specialties: ['', '', ''],
    social: {
      twitter: '#',
      linkedin: '#',
      github: '#',
    },
  },
  {
    id: 'you',
    name: 'You',
    image: null,
    link: 'https://forms.gle/pTMchkVVPCxSVW5u5',
    bio: 'Join our ambassador program',
    specialties: ['Community', 'Innovation', 'Collaboration'],
    isPlaceholder: true,
  },
] as const;

export const AMBASSADOR_BENEFITS = [
  { id: 'free-credits', icon: 'credits' },
  { id: 'feature-preview', icon: 'preview' },
  { id: 'recognition', icon: 'recognition' },
  { id: 'vip-experience', icon: 'vip' },
] as const;

export const AMBASSADOR_RESPONSIBILITIES = [
  { id: 'community-support', icon: 'support' },
  { id: 'content-creation', icon: 'content' },
  { id: 'feedback-provider', icon: 'feedback' },
  { id: 'event-participation', icon: 'events' },
] as const;

export const AMBASSADOR_REQUIREMENTS = [
  { id: 'experience', icon: 'experience' },
  { id: 'community-involvement', icon: 'community' },
  { id: 'communication', icon: 'communication' },
  { id: 'commitment', icon: 'commitment' },
] as const;

export const APPLICATION_CRITERIA = [
  { id: 'passion', icon: 'lamp' },
  { id: 'expertise', icon: 'air-balloon' },
  { id: 'mistral-advocacy', icon: 'codestral' },
  { id: 'commitment', icon: 'magnifying-glass' },
] as const;

export const APPLICATION_INFO = {
  cohort: 'Summer 2025',
  deadline: 'July 1, 2025',
  notification: 'end of July 2025',
  frequency: 'quarterly basis',
  applicationUrl: '#',
  discordUrl: '#',
} as const;

export type AmbassadorData = (typeof AMBASSADORS_DATA)[number];
export type AmbassadorBenefit = (typeof AMBASSADOR_BENEFITS)[number];
export type AmbassadorResponsibility =
  (typeof AMBASSADOR_RESPONSIBILITIES)[number];
export type AmbassadorRequirement = (typeof AMBASSADOR_REQUIREMENTS)[number];
export type ApplicationCriterion = (typeof APPLICATION_CRITERIA)[number];
