import { StaticModel } from '../schema';

export default {
  name: 'Shieldstral 1.0',
  describe: (l) => ({
    description: l.text(`A compact multimodal moderation model for prompt moderation, response moderation, prompt-response pair classification, refusal detection, and safety filtering across text and image inputs. It uses natural-language policy questions and returns a yes or no classification.`, { context: 'Full description of an AI model' }),
    shortDescription: l.text(`Compact multimodal moderation model for text and image safety classification.`, { context: 'Short description of an AI model' }),
  }),
  slug: 'shieldstral-1-0',
  releaseDate: '2026-08-04',
  version: '1.0',
  frontier: true,
  class: 'Specialist',
  type: 'Labs',
  legalButton: null,
  status: 'PublicPreview',
  avatar: { icon: 'shieldstral', backgroundColor: 'beige' },
  weights: [
    {
      name: 'Weights',
      license: 'Apache 2.0',
      licenseUrl: 'https://www.apache.org/licenses/LICENSE-2.0.txt',
      url: 'https://huggingface.co/mistralai/Shieldstral-1.0',
      parameters: '3.8',
      minGpuRam: {
        bf16: null,
        fp8: null,
        fp4: null,
        fp4_16: null,
      },
      active: '3.8',
      contextSize: '32k',
    },
  ],
  bloglink: null,
  paperlink: null,
  contextLength: '32k',
  ratings: {
    speed: 0.0,
    performance: 0.0,
    input: 4.0,
    output: 2.0,
  },
  hideRatings: true,
  pricing: {
    type: 'custom',
    free: false,
    input: [],
    output: [],
  },
  identifiers: { apiNames: [] },
  capabilities: {
    input: ['text', 'image'],
    output: ['text'],
    features: [],
  },
  metadata: { parameters: '3.8B total and active' },
  playground: '',
  legacy: false,
} as const satisfies StaticModel;
