/**
 * T2 — SDK / code samples.
 * Every operation page must ship the three generated SDK samples (typescript,
 * python, curl), the samples must target the operation's path, and the TS sample
 * must be real SDK code. Also sanity-check the SDK tarballs referenced by the
 * docs-md config exist.
 */

import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { loadSpecIndex } from './lib/spec-index';
import { LOCALES, loadRendition, operationSlice, operationsForSlug, readPage } from './lib/rendition';

const spec = loadSpecIndex();
const opCases = spec.operations.map(o => [o.operationId, o] as const);

describe('SDK tarballs referenced by speakeasy.config.mjs exist', () => {
  const config = readFileSync('./speakeasy.config.mjs', 'utf8');
  const tarballs = [...config.matchAll(/sdkTarballPath:\s*'([^']+)'/g)].map(m => m[1]);

  it('config references at least one SDK tarball', () => {
    expect(tarballs.length).toBeGreaterThan(0);
  });

  it.each(tarballs)('tarball exists: %s', tarball => {
    expect(existsSync(tarball), `missing SDK tarball ${tarball}`).toBe(true);
  });
});

describe.each(LOCALES)('SDK samples [%s]', locale => {
  const rendition = loadRendition(locale);

  describe.each(opCases)('%s', (_id, op) => {
    const found = rendition.byOperationId.get(op.operationId);
    const sliceOf = () => {
      if (!found) return '';
      const page = readPage(locale, found.slug) ?? '';
      return operationSlice(page, found.op, operationsForSlug(rendition, found.slug)) ?? '';
    };

    // curl is always generated by docs-md; assert it per operation. (The exact
    // path is validated structurally in coverage.test.ts: rendition.path ===
    // spec.path; the in-sample string is escaped/param-substituted, so not matched here.)
    it('ships a curl sample for the operation', () => {
      if (!found) return; // missing-operation failures belong to the coverage suite
      const slice = sliceOf();
      expect(slice, `no page slice for ${op.operationId}`).toBeTruthy();
      expect(
        slice.includes(`${found.op.elementId}_code-samples_curl`),
        `missing curl sample for ${op.operationId}`
      ).toBe(true);
    });

    // TS/Python only exist where the SDK covers the endpoint (workflows/rag/etc.
    // are curl-only). When present, the sample must be real SDK code, not lorem.
    it('TS/Python samples, when present, are real SDK code', () => {
      if (!found) return;
      const slice = sliceOf();
      if (slice.includes(`${found.op.elementId}_code-samples_typescript`)) {
        expect(slice.includes('@mistralai/mistralai'), `TS sample not SDK code for ${op.operationId}`).toBe(
          true
        );
      }
      if (slice.includes(`${found.op.elementId}_code-samples_python`)) {
        expect(slice.includes('mistralai'), `Python sample not SDK code for ${op.operationId}`).toBe(true);
      }
    });
  });
});
