#!/usr/bin/env bash
set -euo pipefail

# Apply markdownlint fixes from a CSV report with a to_fix column.
#
# Reads the CSV generated by mdlint-report.sh, finds rows where to_fix
# is non-empty, and runs markdownlint --fix for those file×rule combinations.
#
# Granularity: file × rule. If you mark MD009 on file A line 10,
# ALL MD009 errors in file A get fixed. markdownlint can't target
# individual lines — this is the finest granularity available.
#
# Usage:
#   pnpm mdlint:apply                    # reads mdlint-errors.csv
#   pnpm mdlint:apply my-report.csv      # reads a specific CSV

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CSV_FILE="${1:-mdlint-errors.csv}"

# Resolve relative paths against repo root.
if [[ ! "$CSV_FILE" = /* ]]; then
  CSV_FILE="${REPO_ROOT}/${CSV_FILE}"
fi

if [[ ! -f "$CSV_FILE" ]]; then
  echo "Error: CSV file not found: $CSV_FILE"
  exit 1
fi

# ── Parse CSV ────────────────────────────────────────────────────────
# Extract (file, rule) pairs where to_fix is non-empty.
# Output: one "relative_path rule_id" per line, deduplicated.

WORK_DIR=$(mktemp -d /tmp/mdlint-apply-XXXXXX)
trap 'rm -rf "$WORK_DIR"' EXIT

PAIRS_FILE="${WORK_DIR}/pairs.txt"
: > "$PAIRS_FILE"

while IFS=, read -r rule vscode_link description auto_fixable to_fix; do
  # Skip header.
  [[ "$rule" == "rule" ]] && continue

  # Skip rows without to_fix.
  to_fix=$(echo "$to_fix" | tr -d '[:space:]')
  [[ -z "$to_fix" ]] && continue

  # Extract bare rule ID (MD009 from MD009/no-trailing-spaces).
  rule_id="${rule%%/*}"

  # Extract file path from vscode:// link.
  file_path="${vscode_link#vscode://file/}"
  file_path="${file_path%:*}"

  # Make path relative to repo root.
  rel_path="${file_path#${REPO_ROOT}/}"

  echo "${rel_path} ${rule_id}" >> "$PAIRS_FILE"
done < "$CSV_FILE"

# Deduplicate.
sort -u "$PAIRS_FILE" > "${PAIRS_FILE}.dedup"
mv "${PAIRS_FILE}.dedup" "$PAIRS_FILE"

if [[ ! -s "$PAIRS_FILE" ]]; then
  echo "No rows marked with to_fix in $(basename "$CSV_FILE")."
  echo "Open the CSV, put any value in the to_fix column for rows you want fixed, and re-run."
  exit 0
fi

# ── Build per-file rule sets ─────────────────────────────────────────
# For each unique file, collect its rules into a sorted string.

FILES_FILE="${WORK_DIR}/files.txt"
awk '{print $1}' "$PAIRS_FILE" | sort -u > "$FILES_FILE"

RULESETS_DIR="${WORK_DIR}/rulesets"
mkdir -p "$RULESETS_DIR"

while IFS= read -r file; do
  # Collect rules for this file, join as space-separated sorted string.
  ruleset=$(grep "^${file} " "$PAIRS_FILE" | awk '{print $2}' | sort -u | tr '\n' ' ' | sed 's/ $//')

  # Use the ruleset as a filename (spaces replaced with underscores).
  ruleset_key=$(echo "$ruleset" | tr ' ' '_')
  echo "$file" >> "${RULESETS_DIR}/${ruleset_key}.files"
done < "$FILES_FILE"

# ── Apply fixes per batch ────────────────────────────────────────────
# Run markdownlint-cli2 from a temp directory so the project's
# .markdownlint-cli2.jsonc is NOT picked up. The temp directory gets
# its own config with only the selected rules enabled.

total_files=0
for ruleset_file in "${RULESETS_DIR}"/*.files; do
  [[ -f "$ruleset_file" ]] || continue

  # Recover the ruleset from the filename.
  ruleset_key=$(basename "$ruleset_file" .files)
  ruleset=$(echo "$ruleset_key" | tr '_' ' ')

  # Build a standalone config in the temp directory.
  RUN_DIR="${WORK_DIR}/run"
  rm -rf "$RUN_DIR"
  mkdir -p "$RUN_DIR"

  tmp_config="${RUN_DIR}/.markdownlint-cli2.jsonc"
  {
    echo '{'
    echo '  "markdownExtensions": [".mdx"],'
    echo '  "config": {'
    echo '    "default": false,'
    first=true
    for r in $ruleset; do
      $first || printf ',\n'
      printf '    "%s": true' "$r"
      first=false
    done
    printf '\n'
    echo '  }'
    echo '}'
  } > "$tmp_config"

  # Collect absolute file paths, escaping glob-special characters.
  file_args=()
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    abs="${REPO_ROOT}/${f}"
    # Escape parentheses so markdownlint-cli2 doesn't treat them as globs.
    abs="${abs//\(/\\(}"
    abs="${abs//\)/\\)}"
    file_args+=("$abs")
  done < "$ruleset_file"

  count=${#file_args[@]}
  total_files=$((total_files + count))
  echo "Fixing ${count} file(s) — rules: ${ruleset}"

  # Use the project's markdownlint-cli2 binary directly.
  MDLINT_BIN="${REPO_ROOT}/node_modules/.bin/markdownlint-cli2"
  (cd "$RUN_DIR" && "$MDLINT_BIN" --fix "${file_args[@]}" 2>&1) || true
done

echo ""
echo "Applied fixes to ${total_files} file(s)."
echo "Run 'pnpm mdlint:report' to regenerate the report and verify."
