export type PlatformFeature = {
    id: string;
    name: string;
    shortDescription: string;
    description: string;
    tags: string[];
    icon: string;
    interfaceType: 'Le Chat' | 'Studio' | 'Mistral Vibe' | 'Admin';
};

export const platformFeaturesData: PlatformFeature[] = [
    // LE CHAT
    {
        id: 'le-chat-chat',
        name: 'Chat',
        shortDescription: 'Conversational AI interface',
        description: "The core conversational interface powered by Mistral's latest models. Features multi-turn context retention, multilingual support, and a responsive multi-modal experience for everyday productivity tasks.",
        tags: ['Multi-modal', 'Multilingual'],
        icon: 'message-square',
        interfaceType: 'Le Chat',
    },
    {
        id: 'le-chat-deep-research',
        name: 'Deep Research',
        shortDescription: 'Autonomous web research & reporting',
        description: 'Le Chat autonomously plans a research strategy, navigates the web to synthesize multiple trusted sources, and generates long-form analytical reports.',
        tags: ['Browsing', 'Synthesis', 'Reports'],
        icon: 'search',
        interfaceType: 'Le Chat',
    },
    {
        id: 'le-chat-document-intel',
        name: 'Document Intelligence',
        shortDescription: 'Upload & analyze files with OCR',
        description: 'Upload PDFs, spreadsheets, and Word documents directly into chat. Le Chat applies OCR 3 natively to extract text from scanned images and complex document layouts.',
        tags: ['PDFs', 'OCR 3', 'Analysis'],
        icon: 'file-text',
        interfaceType: 'Le Chat',
    },
    {
        id: 'le-chat-code-interpreter',
        name: 'Code Interpreter',
        shortDescription: 'Run Python natively in chat',
        description: 'A secure Python sandbox directly within Le Chat. Upload datasets to explore data, generate charts, and automate data transformations without leaving your browser.',
        tags: ['Python', 'Data', 'Charts'],
        icon: 'code',
        interfaceType: 'Le Chat',
    },
    {
        id: 'le-chat-canvas',
        name: 'Canvas',
        shortDescription: 'Real-time collaborative editing',
        description: "An integrated writing and coding surface. Le Chat generates text, code, or presentations, allowing you to collaboratively refine and edit the AI's output in real time.",
        tags: ['Documents', 'Code', 'Inline Edits'],
        icon: 'pen-tool',
        interfaceType: 'Le Chat',
    },
    {
        id: 'le-chat-memories',
        name: 'Memories & Libraries',
        shortDescription: 'Cross-conversation context storage',
        description: "Enable Memories to let Le Chat retain your preferences across sessions. Build Libraries from uploaded documents to ground the model's responses in your own secure knowledge base.",
        tags: ['Context', 'RAG', 'Knowledge'],
        icon: 'briefcase',
        interfaceType: 'Le Chat',
    },
    {
        id: 'le-chat-agents',
        name: 'Custom Agents',
        shortDescription: 'Customizable AI assistants',
        description: 'Create AI assistants for specific workflows. Define custom system instructions, attach tools (like MCP connectors), link knowledge bases, and share them securely with your team.',
        tags: ['Assistants', 'Tools', 'Teams'],
        icon: 'bot',
        interfaceType: 'Le Chat',
    },
    // MISTRAL VIBE
    {
        id: 'vibe-terminal',
        name: 'Terminal Agent',
        shortDescription: 'Conversational coding in your terminal',
        description: 'A conversational interface to your codebase, right in the terminal. Reference files with @, run shell commands with !, and use slash-command skills to automate common workflows.',
        tags: ['CLI', 'Devstral', 'Terminal'],
        icon: 'code',
        interfaceType: 'Mistral Vibe',
    },
    {
        id: 'vibe-agents-skills',
        name: 'Agents & Skills',
        shortDescription: 'Custom agents with reusable skills',
        description: 'Build custom agents with system prompts and reusable slash-command skills. Automate repetitive workflows like code review, test generation, and documentation updates.',
        tags: ['Agents', 'Automation', 'Skills'],
        icon: 'bot',
        interfaceType: 'Mistral Vibe',
    },
    {
        id: 'vibe-ide-integration',
        name: 'IDE Integration',
        shortDescription: 'JetBrains and Zed support',
        description: 'Integrate Mistral Vibe with JetBrains and Zed via the Agent Communication Protocol. Get AI assistance directly in your editor while keeping terminal access.',
        tags: ['JetBrains', 'Zed'],
        icon: 'code',
        interfaceType: 'Mistral Vibe',
    },
    {
        id: 'vibe-local',
        name: 'Local Mode',
        shortDescription: 'Fully offline with local models',
        description: 'Run Mistral Vibe offline with locally deployed models. Keep your code on your machine with no data leaving your environment, while retaining full agent capabilities.',
        tags: ['Offline', 'Privacy', 'Local'],
        icon: 'lock',
        interfaceType: 'Mistral Vibe',
    },

    // STUDIO
    {
        id: 'studio-playground',
        name: 'Playground',
        shortDescription: 'Interactive prompt & parameter testing',
        description: 'A visual lab to experiment with system prompts, user messages, and generation parameters (like Temperature and Top-P). Test prompts side-by-side across different Mistral models instantly.',
        tags: ['Parameters', 'Side-by-side'],
        icon: 'mouse-pointer',
        interfaceType: 'Studio',
    },
    {
        id: 'studio-api-keys',
        name: 'API Keys',
        shortDescription: 'Workspace-scoped access tokens',
        description: 'Generate and securely manage programmatic access tokens. API keys are scope-limited to specific workspaces, allowing precise control over which applications can access specific resources.',
        tags: ['Auth', 'Tokens', 'Rotation'],
        icon: 'key',
        interfaceType: 'Studio',
    },
    {
        id: 'studio-finetuning',
        name: 'Fine-tuning',
        shortDescription: 'Custom model training via API',
        description: 'Train custom Mistral models on your own datasets via JSONL file uploads. Adapt base models to your domain terminology, tone, or specific formatting tasks.',
        tags: ['JSONL', 'LoRA', 'Training'],
        icon: 'settings',
        interfaceType: 'Studio',
    },
    {
        id: 'studio-evaluation',
        name: 'Evaluation',
        shortDescription: 'Systematic benchmark testing',
        description: 'Run benchmark pipelines against your fine-tuned deployments or complex system prompts to objectively measure accuracy, performance, and detect regressions over time.',
        tags: ['Datasets', 'Performance'],
        icon: 'activity',
        interfaceType: 'Studio',
    },
    {
        id: 'studio-agents-api',
        name: 'Agents API',
        shortDescription: 'Programmatic agent execution',
        description: 'Deploy custom agents into production. The Agents API allows developers to programmatically execute workflows where Mistral models autonomously orchestrate external tool calling.',
        tags: ['Production', 'Tools', 'API'],
        icon: 'bot',
        interfaceType: 'Studio',
    },

    // ADMIN
    {
        id: 'admin-users',
        name: 'User Management',
        shortDescription: 'Manage members, roles & seats',
        description: 'Centrally administer your organization. Invite team members, enforce secure Admin/Billing/Member roles, and allocate paid seats for premium products like Vibe Team and Mistral Code.',
        tags: ['Roles', 'Seats', 'Access'],
        icon: 'users',
        interfaceType: 'Admin',
    },
    {
        id: 'admin-sso',
        name: 'Single Sign-On (SSO)',
        shortDescription: 'SAML-based authentication',
        description: 'Mandate corporate security policies by connecting Mistral Platform to your existing identity provider via SAML SSO. Includes secure domain name verification to claim organizational domains.',
        tags: ['SAML', 'Identity', 'Domains'],
        icon: 'shield',
        interfaceType: 'Admin',
    },
    {
        id: 'admin-workspaces',
        name: 'Workspaces',
        shortDescription: 'Isolated team environments',
        description: 'Divide your organization into distinct, secure workspaces. Isolate API keys, fine-tuned models, and billing groups so that different departments operations never overlap.',
        tags: ['Isolation', 'Projects', 'Namespaces'],
        icon: 'briefcase',
        interfaceType: 'Admin',
    },
    {
        id: 'admin-billing',
        name: 'Billing & Limits',
        shortDescription: 'Invoices & spending controls',
        description: 'Monitor token expenditure in real time. Download invoices, update payment methods, and establish strict hard spending caps per workspace to completely prevent unexpected cost overruns.',
        tags: ['Payments', 'Budgets', 'Caps'],
        icon: 'credit-card',
        interfaceType: 'Admin',
    },
    {
        id: 'admin-audit',
        name: 'Audit Logs',
        shortDescription: 'Compliance & usage tracking',
        description: 'Maintain a strict, chronological record of organizational events. Track when users are invited, when API keys are generated, and view security events for internal compliance auditing.',
        tags: ['Compliance', 'Export', 'Tracking'],
        icon: 'file-text',
        interfaceType: 'Admin',
    },
    {
        id: 'admin-privacy',
        name: 'Data Privacy Controls',
        shortDescription: 'GDPR & training opt-outs',
        description: 'Take full control of data sovereignty. Admins can globally opt out of data collection for model training, manage data retention policies, and execute strict GDPR deletion requests.',
        tags: ['GDPR', 'Opt-out', 'Policy'],
        icon: 'shield',
        interfaceType: 'Admin',
    },
];
