# If the public docs repository is tagged, prepare the corresponding update PR.

name: Build and Publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  create_pr_on_public:
    permissions:
      contents: read
      id-token: write
    uses: mistralai/platform-docs-public/.github/workflows/publish_tag.yml@main
    secrets: inherit
